#!/bin/bash
# create-opencode-agent.sh — add an acpx reviewer backed by any provider opencode
# already knows.
#
# Usage: create-opencode-agent.sh <name> <provider/model> [env_var] [context] [output]
#
#   name          — acpx agent name, and what you put in `agent` in debate-acpx.json
#   provider/model— as opencode names it, e.g. deepseek/deepseek-reasoner
#   env_var       — env var holding the key (default: <PROVIDER>_API_KEY)
#   context       — context window to declare (default: leave opencode's own)
#   output        — max output tokens (default: 8000, see the note below)
#
# Chain: acpx -> opencode (ACP mode) -> the provider's own API.
#
# This is the sibling of create-litellm-agent.sh, and the two cover different
# cases. Use this one when opencode already has the provider in its catalogue
# (check https://models.dev) — the request goes straight to the provider and
# there is nothing else to run. Use the LiteLLM script when it does not: a local
# proxy, an unlisted endpoint, or anything that needs rewriting on the way out.
#
# The key is read at review time, never written into the wrapper. Three places are
# tried, in order:
#
#   1. $<PROVIDER>_API_KEY
#   2. ~/.claude/debate-keys.json  -> {"<provider>": "sk-..."}
#   3. ~/.claude/debate-<provider>.json -> {"api_key": "sk-..."}
#
# (2) is the one to use: one file for every provider's key, one thing to chmod 600
# and to back up. It is deliberately NOT debate-acpx.json — that file has a sample
# twin in the repo and is safe to paste into a bug report, which stops being true
# the moment it holds credentials. (3) is kept because the OpenRouter seats have
# always read their key that way.
#
# After running this:
#   1. Add a reviewer to ~/.claude/debate-acpx.json with "agent": "<name>"
#   2. Run /debate:acpx-setup to probe it

set -euo pipefail

NAME="${1:-}"
PROVIDER_MODEL="${2:-}"
ENV_VAR="${3:-}"
CONTEXT="${4:-}"
OUTPUT="${5:-8000}"

if [ -z "$NAME" ] || [ -z "$PROVIDER_MODEL" ]; then
  echo "Usage: $0 <name> <provider/model> [env_var] [context] [output]" >&2
  echo "" >&2
  echo "Examples:" >&2
  echo "  $0 deepseek deepseek/deepseek-reasoner" >&2
  echo "  $0 deepseek-pro deepseek/deepseek-v4-pro DEEPSEEK_API_KEY 1000000 8000" >&2
  echo "" >&2
  echo "provider/model must be one opencode knows — see https://models.dev" >&2
  exit 2
fi

case "$PROVIDER_MODEL" in
  */*) ;;
  *)
    echo "create-opencode-agent: '$PROVIDER_MODEL' is not provider/model" >&2
    exit 2
    ;;
esac

PROVIDER="${PROVIDER_MODEL%%/*}"
MODEL="${PROVIDER_MODEL#*/}"

if [ -z "$ENV_VAR" ]; then
  # deepseek -> DEEPSEEK_API_KEY. tr keeps this portable; ${x^^} is bash 4 only
  # and macOS ships bash 3.2.
  ENV_VAR="$(printf '%s' "$PROVIDER" | tr '[:lower:]-' '[:upper:]_')_API_KEY"
fi

if ! command -v opencode > /dev/null 2>&1; then
  echo "create-opencode-agent: opencode not found — install it first (it is the ACP bridge)." >&2
  exit 1
fi

AGENT_DIR="${HOME}/.acpx/agents/${NAME}"
START_SH="${AGENT_DIR}/start.sh"

echo "Creating opencode agent wrapper: ${NAME}" >&2
echo "  Model:      ${PROVIDER}/${MODEL}" >&2
echo "  Key from:   \$${ENV_VAR}, else ~/.claude/debate-${PROVIDER}.json" >&2
echo "  Agent dir:  ${AGENT_DIR}" >&2

mkdir -p "${AGENT_DIR}"

# The model block is only emitted when a context window was given, so the default
# is whatever opencode already believes about the model rather than a number this
# script invented.
if [ -n "$CONTEXT" ]; then
  MODELS_BLOCK=", \"models\": {\"${MODEL}\": {\"limit\": {\"context\": ${CONTEXT}, \"output\": ${OUTPUT}}}}"
else
  MODELS_BLOCK=""
fi

cat > "${START_SH}" << STARTSH
#!/bin/bash
# acpx agent: ${NAME}
# Generated by create-opencode-agent.sh — edit freely, it is not regenerated.
#
# ${PROVIDER}/${MODEL}, served through opencode's ACP mode straight to the
# provider. No proxy in the path.

set -euo pipefail

# Environment, then the shared keys file, then the per-provider one. A reviewer
# that starts without a key does not fail loudly — opencode ends the turn with no
# message, which the runner reports as a blank review — so refuse here instead,
# where the reason is still visible.
KEY="\${${ENV_VAR}:-}"
if [ -z "\$KEY" ]; then
  KEY="\$(python3 -c '
import json, os, stat, sys

def read(path, *keys):
    p = os.path.expanduser(path)
    try:
        st = os.stat(p)
    except OSError:
        return ""
    # A key file the rest of the machine can read is the same as no key file at
    # all, security-wise, and it drifts there easily — an editor, a restore from
    # backup, a copy with the wrong umask. Fix it rather than warn about it.
    if st.st_mode & (stat.S_IRWXG | stat.S_IRWXO):
        try:
            os.chmod(p, 0o600)
            sys.stderr.write("[keys] tightened %s to 600\n" % p)
        except OSError:
            sys.stderr.write("[keys] WARNING: %s is readable by other accounts and could not be chmodded\n" % p)
    try:
        d = json.load(open(p))
    except Exception:
        return ""
    for k in keys:
        v = d.get(k)
        if isinstance(v, str) and v:
            return v
    return ""

print(read("~/.claude/debate-keys.json", "${PROVIDER}")
      or read("~/.claude/debate-${PROVIDER}.json", "api_key"))
')"
fi

if [ -z "\$KEY" ]; then
  echo "[${NAME}] no API key. Set \\\$${ENV_VAR}, or add \"${PROVIDER}\": \"sk-...\" to ~/.claude/debate-keys.json (chmod 600)." >&2
  exit 1
fi

# The key reaches python through the environment, never through the command text,
# so it cannot be read out of another process's arguments.
export OPENCODE_AGENT_KEY="\$KEY"

export OPENCODE_CONFIG_CONTENT="\$(python3 -c '
import json, os
print(json.dumps({
    "model": "${PROVIDER}/${MODEL}",
    "provider": {
        "${PROVIDER}": {
            "options": {"apiKey": os.environ["OPENCODE_AGENT_KEY"]}${MODELS_BLOCK}
        }
    },
}))
')"

exec opencode acp "\$@"
STARTSH

chmod +x "${START_SH}"

# Register in ~/.acpx/config.json. Writing the wrapper is not enough — acpx resolves
# an agent through this map, not by looking in the agents directory, and an
# unregistered name fails at spawn with "Failed to spawn agent command: <name>",
# which reads like a broken wrapper rather than a missing line of config.
ACPX_CONFIG="${HOME}/.acpx/config.json"

if [ -f "${ACPX_CONFIG}" ]; then
  if command -v jq > /dev/null 2>&1; then
    MERGED=$(jq --arg name "${NAME}" --arg cmd "${START_SH}" \
      '.agents[$name] = {"command": $cmd}' "${ACPX_CONFIG}")
    printf '%s\n' "${MERGED}" > "${ACPX_CONFIG}"
    echo "  Registered in ${ACPX_CONFIG}" >&2
  else
    echo "  WARNING: jq not found — ${NAME} is NOT registered and will not spawn." >&2
    echo "  Add to ${ACPX_CONFIG} by hand:" >&2
    echo "    { \"agents\": { \"${NAME}\": { \"command\": \"${START_SH}\" } } }" >&2
  fi
else
  mkdir -p "${HOME}/.acpx"
  printf '{\n  "agents": {\n    "%s": {\n      "command": "%s"\n    }\n  }\n}\n' \
    "${NAME}" "${START_SH}" > "${ACPX_CONFIG}"
  echo "  Created ${ACPX_CONFIG}" >&2
fi

echo "" >&2
echo "Created ${START_SH}" >&2
echo "" >&2
echo "Next:" >&2
echo "  1. Add the key to ~/.claude/debate-keys.json as {\"${PROVIDER}\": \"...\"}" >&2
echo "     then: chmod 600 ~/.claude/debate-keys.json   (\$${ENV_VAR} also works)" >&2
echo "  2. Add a reviewer to ~/.claude/debate-acpx.json:" >&2
echo "       \"${NAME}\": { \"agent\": \"${NAME}\", \"timeout\": 600, \"mode\": \"exec\", \"retries\": 2," >&2
echo "                    \"system_prompt\": \"...\" }" >&2
echo "  3. Probe it: /debate:acpx-setup" >&2
